/*
var test = [
[
{title:"what were the names of the two most popular boybands of the 90s?",
answers:["bsb and nsync","1-D and 5ive","take that and nkotb"],
correct: "bsb and nsync"}, 
{title:"which girlband released their hit single 'wannabe' in 1996?",
answers:["spice girls","funky diamonds","solid harmony"],
correct:"spice girls"}, 
{title:"which band was a grunge band from seattle?",
answers:["captain jack", "stone temple pilots", "pearl jam"],
correct:"pearl jam"},
{title:"what was the name of the dance music genre popular in the 90s?",
answers:["eurodance","edm","deep house"],
correct:"eurodance"},
{title:"what was the name of irish band consisting of family members?",
answers:["the moffats", "hanson","the kelly family"],
correct:"the kelly family"},
{title:"which of these soap operas did not run in the 90s?",
answers:["sex and the city", "gossip girl", "friends"],
correct:"gossip girl"},
{title:"what is the  other name of a state which is a birthplace of grunge music?",
answers:["the rainy state", "the evergreen state", "garden state"],
correct:"the evergreen state"},
{title:"two frenemies from the popular 90s soap opera 'beverly hills 90210' were named...",
answers:["blair and serena", "brenda and kelly", "monica and rachel"],
correct:"brenda and kelly"},
{title:"justin timberlake's first band was...",
answers:["nkotb", "bsb", "nsync"],
correct:"nsync"},
{title:"what were the names of electronic toys kept as pets?",
answers:["furigi and tamaru", "furby and tamagotchi", "tamagoru and fibura"],
correct:"furby and tamagotchi"},
{title:"what year was JavaScript invented in?",
answers:["1996", "1992", "1995"],
correct:"1995"},
{title:"what was the name of the british boyband where robbie williams started his career?",
answers:["take that", "boyzone", "east-17"],
correct:"take that"}
],

[{title:"which boyband sung 'quit playing games'?",
answers:["backstreet boys", "nsync", "take that"],
correct:"backstreet boys"},
{title:"which of these boys did not decide to go solo?",
answers:["nick carter", "justin timberlake", "owen williams"],
correct:"owen williams"},
{title:"who covered george michael's 'freedom' after leaving his band?",
answers:["nick carter", "justin timberlake", "robbie williams"],
correct:"robbie williams"},
{title:"those two bandmates really hated each other but reconciled in 2010. they are...",
answers:["nick carter & brian littrel", "justin timberlake and jc chasez", "robbie williams & gary barlow"],
correct:"robbie williams & gary barlow"},
{title:"those two bands are british:",
answers:["five & take that", "east 17 & nkotb", "nsync and bsb"],
correct: "five & take that"},
{title:"these two bands are irish:",
answers:["take that & nkotb", "east 17 & 98degrees", "westlife & boyzone"],
correct: "westlife & boyzone"},
{title:"'if you got the feeling' is a song by...",
answers:["five", "east 17", "backstreet boys"],
correct: "five"},
{title:"backstreet boys' first hit single was released in...",
answers:["1995", "1994", "1997"],
correct: "1995"},
{title:"touche are a boyband from...",
answers:["germany", "belgium", "france"],
correct: "germany"},
{title:"how many members did 98degrees have?",
answers:["five", "three", "four"],
correct: "four"}
],
[{title:"what was the name of paddy kelly's brother?",
answers:["aaron", "bobbie", "angelo"],
correct:"angelo"},
{title:"which band sung 'blackhole sun?",
answers:["soundgarden", "the smashing pumpkins", "nirvana"],
correct:"soundgarden"},
{title:"whose brother dated lindsay lohan in early 2000s?",
answers:["nick carter's", "justin timberlake's", "mark owen's"],
correct:"nick carter's"},
{title:"member of which irish boyband came out to the public?",
answers:["nsync", "take that", "boyzone"],
correct:"boyzone"},
{title:"who dated paris hilton?",
answers:["lance bass", "nick carter", "justin timberlake"],
correct: "nick carter"},
{title:"kurt cobain's wife's name was...",
answers:["jessica simpson", "geri halliwell", "courtney love"],
correct: "courtney love"},
{title:"which band had a duet with queen?",
answers:["five", "boyzone", "take that"],
correct: "five"},
{title:"furby was invented in...",
answers:["1995", "1998", "1997"],
correct: "1998"},
{title:"what is the name of pop dance festival held in Germany and Austria?",
answers:["The Doom", "The Dance Off", "The Dome"],
correct: "The Dome"},
{title:"Nirvana's artist Dave Grohl founded another band in 1995. It was...",
answers:["Our Lady Peace", "Foo Fighters", "Smashing Pumpkins"],
correct: "Foo Fighters"}
],
[{title:"who was the dark haired female lead in gossip girl",
answers:["blair", "serena", "jenny"],
correct:"blair"},
{title:"who was blair's boyfriend in season one?",
answers:["nate archibald", "chuck bass", "carter baizen"],
correct:"nate archibald"},
{title:"serena's mother's name is...",
answers:["lilly", "rose", "charlotte"],
correct:"lilly"},
{title:"chuck bass' dog's name is...",
answers:["chipmunk", "monkey", "buzzer"],
correct:"monkey"},
{title:"serena's grandmother's name is...",
answers:["cece van der woodsen", "cece vanderbildt", "cece rhodes"],
correct: "cece rhodes"},
{title:"how many times was serena's mother married?",
answers:["four", "seven", "three"],
correct: "seven"},
{title:"who was the real gossip girl",
answers:["dorota", "eric", "dan"],
correct: "dan"},
{title:"gossip girl aired in poland for the firts time in...",
answers:["2005", "2008", "2007"],
correct: "2008"},
{title:"what are blair's favourite flowers",
answers:["petunias", "peonies", "roses"],
correct: "peonies"},
{title:"serena van der woodsen's middle name is...",
answers:["catherine", "lillian", "celia"],
correct: "celia"}
],

];


*/

